#c=input("Hello:")

fp=open("syslog1",'r')
fo=open("test181018.txt","w")
count = len(fp.readlines())
fp.close()
fa=open("syslog1",'r')
for i in range(count):
  string1=fa.readline()
  string2=string1[132:]
  string3=string2[:22]+","+string2[23:]
  string3=string3.replace(" duration","=duration")
  string3=string3.replace(" policy_id","=policy_id")
  string3=string3.replace(" service","=service")
  string3=string3.replace(" proto","=proto")
  string3=string3.replace(" src","=src")
  string3=string3.replace(" dst","=dst")
  string3=string3.replace(" action","=action")
  string3=string3.replace(" sent","=sent")
  string3=string3.replace(" rcvd","=rcvd")
  string3=string3.replace(" port","=port")
  string3=string3.replace(" session","=session")
  string3=string3.replace(" reason","=reason")
  string3=string3.replace("id=8","id=8(U2T_https)")
  string3=string3.replace("id=4","id=4(U2T_http)")
  string3=string3.replace("id=9","id=9(U2T_smtp)")
  string3=string3.replace("id=28","id=28(T2U_1935)")
  string3=string3.replace("id=21","id=21(T2U_cs00)")
  string3=string3.replace("id=17","id=17(T2U_.7)")
  string3=string3.replace("id=12","id=12(T2U_cs02)")
  string3=string3.replace("id=14","id=14(T2U_cs01)")
  string3=string3.replace("id=22","id=22(T2U_.2)")
  string3=string3.replace("id=29","id=22(T2U_cs00no)")
  fo.write(string3)


#print(count)
fa.close()
fo.close()